spring:
  datasource:
    menu:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/cert?allowMultiQueries=true&amp;useLocalSessionState=true&amp;autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver